-- AlterTable
ALTER TABLE `PositionPermission` MODIFY `value` ENUM('LEADER', 'SECOND_IN_COMMAND', 'LEADERSHIP', 'MANAGE_MEMBERS', 'MANAGE_POSITIONS', 'MANAGE_ASSETS', 'MANAGE_RANKS', 'MANAGE_REPORTS', 'OVERRIDE_SECURITY', 'MANAGE_SECURITY', 'MONITOR_ACTIVITY', 'CREATE_REPORTS', 'MANAGE_SUBORGANIZATIONS', 'VIEW_AUDIT_LOGS', 'APPROVE_CLEARANCES', 'GRANT_HONORS') NOT NULL;
