-- CreateTable
CREATE TABLE `PositionPermission` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `value` ENUM('LEADER', 'SECOND_IN_COMMAND', 'LEADERSHIP', 'MANAGE_MEMBERS', 'MANAGE_POSITIONS', 'MANAGE_ASSETS', 'MANAGE_RANKS', 'MANAGE_REPORTS', 'OVERRIDE_SECURITY', 'MANAGE_SECURITY', 'MONITOR_ACTIVITY') NOT NULL,
    `positionId` BIGINT NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `PositionPermission` ADD CONSTRAINT `PositionPermission_positionId_fkey` FOREIGN KEY (`positionId`) REFERENCES `Position`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
