-- DropForeignKey
ALTER TABLE `Account` DROP FOREIGN KEY `Account_userId_fkey`;

-- DropIndex
DROP INDEX `Account_userId_key` ON `Account`;

-- AlterTable
ALTER TABLE `PositionPermission` MODIFY `value` ENUM('LEADER', 'SECOND_IN_COMMAND', 'LEADERSHIP', 'MANAGE_MEMBERS', 'MANAGE_POSITIONS', 'MANAGE_ASSETS', 'MANAGE_RANKS', 'MANAGE_REPORTS', 'OVERRIDE_SECURITY', 'MANAGE_SECURITY', 'MONITOR_ACTIVITY', 'CREATE_REPORTS') NOT NULL;
