-- AlterTable
ALTER TABLE `Oversector` ADD COLUMN `color` VARCHAR(7) NULL,
    ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `height` DOUBLE NOT NULL DEFAULT 1000,
    ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `width` DOUBLE NOT NULL DEFAULT 1000,
    ADD COLUMN `x` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `y` DOUBLE NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `Planet` ADD COLUMN `color` VARCHAR(7) NULL,
    ADD COLUMN `radius` DOUBLE NOT NULL DEFAULT 5,
    ADD COLUMN `x` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `y` DOUBLE NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `Sector` ADD COLUMN `color` VARCHAR(7) NULL,
    ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `height` DOUBLE NOT NULL DEFAULT 200,
    ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `width` DOUBLE NOT NULL DEFAULT 200,
    ADD COLUMN `x` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `y` DOUBLE NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `System` ADD COLUMN `color` VARCHAR(7) NULL,
    ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `height` DOUBLE NOT NULL DEFAULT 50,
    ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `width` DOUBLE NOT NULL DEFAULT 50,
    ADD COLUMN `x` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `y` DOUBLE NOT NULL DEFAULT 0;
